package database

const createProductSchema = `
CREATE TABLE IF NOT EXISTS products (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	label VARCHAR(30) NOT NULL DEFAULT '',
	quantity INT UNSIGNED NOT NULL DEFAULT 0,
	price DECIMAL(7,2) NOT NULL DEFAULT 99999.99,
	PRIMARY KEY  (id)
  )
`

const insertProduct = `
INSERT INTO PRODUCTS(LABEL, PRICE, QUANTITY)
VALUES(?, ?, ?)
`